export function createPageUrl(pageName) {
  const routes = {
    'Home': '/',
    'Shop': '/shop',
    'ProductDetail': '/product',
    'Cart': '/cart',
    'Checkout': '/checkout',
    'Orders': '/orders',
    'OrderConfirmation': '/order-confirmation',
    'Wishlist': '/wishlist',
    'About': '/about',
    'Contact': '/contact',
    'FAQ': '/faq',
    'Privacy': '/privacy',
    'Terms': '/terms',
    'Returns': '/returns',
    'Login': '/login',
    'AdminDashboard': '/admin',
    'AdminAnalytics': '/admin/analytics',
    'AdminProducts': '/admin/products',
    'AdminCategories': '/admin/categories',
    'AdminOrders': '/admin/orders',
    'AdminCustomers': '/admin/customers',
    'AdminCoupons': '/admin/coupons',
    'AdminBanners': '/admin/banners',
    'AdminBlog': '/admin/blog',
    'AdminPages': '/admin/pages',
    'AdminPayments': '/admin/payments',
    'AdminShipping': '/admin/shipping',
    'AdminTaxes': '/admin/taxes',
    'AdminSettings': '/admin/settings',
    'AdminBusiness': '/admin/business',
  };
  return routes[pageName] || '/';
}

